export type TransactionType = 'income' | 'expense';

export type IncomeFrequency = 'weekly' | 'biweekly' | 'monthly';

export interface Person {
  id: string;
  name: string;
  color: string;
  /** Regular income in cents, earned every `incomeFrequency` */
  incomeCents: number;
  incomeFrequency: IncomeFrequency;
}

export interface Category {
  id: string;
  name: string;
  emoji: string;
}

export interface Transaction {
  id: string;
  personId: string;
  type: TransactionType;
  /** Amount in cents to avoid floating point issues */
  amountCents: number;
  note: string;
  /** ISO date string (yyyy-mm-dd) */
  date: string;
  /** Whether this expense is shared between people (only relevant for expenses) */
  shared: boolean;
  /** Category (expenses only) */
  categoryId?: string;
  /** Set when this entry was generated by a recurring rule */
  recurringId?: string;
}

/** A repeating income or expense (rent, salary, subscription, …) */
export interface RecurringRule {
  id: string;
  personId: string;
  type: TransactionType;
  amountCents: number;
  note: string;
  shared: boolean;
  categoryId?: string;
  frequency: IncomeFrequency;
  /** Date of the first occurrence (yyyy-mm-dd) */
  anchorDate: string;
  /** Date of the last occurrence that was turned into a transaction */
  lastAppliedDate?: string;
}

export type SplitMethod = 'fifty-fifty' | 'percentage' | 'equal-payments';

/** Settlements can cover a calendar month or an ISO week */
export type PeriodType = 'month' | 'week';

export interface PersonResult {
  personId: string;
  personName: string;
  paidCents: number;
  shareCents: number;
  /** paid - share: positive means this person is owed money */
  netCents: number;
  /** Only set for percentage method */
  percentage?: number;
}

export interface Transfer {
  fromName: string;
  toName: string;
  amountCents: number;
}

export interface SettlementRecord {
  id: string;
  periodType: PeriodType;
  /** yyyy-mm for months, yyyy-Www for ISO weeks */
  period: string;
  method: SplitMethod;
  totalSharedCents: number;
  results: PersonResult[];
  transfers: Transfer[];
  /** ISO timestamp of when the calculation was saved */
  createdAt: string;
}

export interface AppSettings {
  themeMode: 'light' | 'dark' | 'auto';
  /** Whether the first-launch setup has been completed */
  onboarded: boolean;
  /** ISO 4217 code of the display currency */
  currencyCode: string;
  /** Require biometric/device unlock when opening the app */
  appLock: boolean;
}

export interface AppState {
  people: Person[];
  transactions: Transaction[];
  settlements: SettlementRecord[];
  recurring: RecurringRule[];
  customCategories: Category[];
  /** Monthly spending limit in cents per category id */
  budgets: Record<string, number>;
  settings: AppSettings;
}
