export type TransactionType = 'income' | 'expense';

export type IncomeFrequency = 'weekly' | 'biweekly' | 'monthly';

export interface Person {
  id: string;
  name: string;
  color: string;
  /** Regular income in cents, earned every `incomeFrequency` */
  incomeCents: number;
  incomeFrequency: IncomeFrequency;
}

export type AccountKind = 'cash' | 'bank' | 'savings';

/** Where money physically sits */
export interface Account {
  id: string;
  name: string;
  kind: AccountKind;
  color: string;
  /** Balance before the first tracked entry */
  openingCents: number;
}

/** Money moved between two accounts — neither income nor expense */
export interface AccountTransfer {
  id: string;
  fromAccountId: string;
  toAccountId: string;
  amountCents: number;
  date: string;
  note: string;
}

export interface Category {
  id: string;
  name: string;
  /** Dot color shown in lists; subcategories inherit their parent's */
  color: string;
  /** Set on subcategories; absent on top-level categories */
  parentId?: string;
}

export interface Transaction {
  id: string;
  personId: string;
  type: TransactionType;
  /** Amount in cents to avoid floating point issues */
  amountCents: number;
  note: string;
  /** ISO date string (yyyy-mm-dd) */
  date: string;
  /** Whether this expense is shared between people (only relevant for expenses) */
  shared: boolean;
  /** Category (expenses only) */
  categoryId?: string;
  /** Set when this entry was generated by a recurring rule */
  recurringId?: string;
  /** Local file URI of an attached receipt photo */
  photoUri?: string;
  /** Which account the money came from or landed in */
  accountId?: string;
  /**
   * Free-form labels, stored lowercased. Categories answer "what kind of
   * spending"; tags answer "which project" — a holiday, a renovation — and
   * cut across categories.
   */
  tags?: string[];
}

/**
 * A saved entry shape that can be re-added in one tap. Deliberately holds no
 * date: a template is the shape of a recurring purchase, not an occurrence.
 */
export interface EntryTemplate {
  id: string;
  name: string;
  personId: string;
  type: TransactionType;
  amountCents: number;
  note: string;
  shared: boolean;
  categoryId?: string;
  accountId?: string;
  tags?: string[];
}

/** A repeating income or expense (rent, salary, subscription, …) */
export interface RecurringRule {
  id: string;
  personId: string;
  type: TransactionType;
  amountCents: number;
  note: string;
  shared: boolean;
  categoryId?: string;
  /** Carried onto every entry the rule generates */
  tags?: string[];
  frequency: IncomeFrequency;
  /** Date of the first occurrence (yyyy-mm-dd) */
  anchorDate: string;
  /** Date of the last occurrence that was turned into a transaction */
  lastAppliedDate?: string;
}

export type SplitMethod = 'fifty-fifty' | 'percentage' | 'equal-payments';

/** Settlements can cover a calendar month or an ISO week */
export type PeriodType = 'month' | 'week';

/** Periods usable in navigation and stats; settlements stay month/week */
export type NavPeriodType = PeriodType | 'year';

export interface PersonResult {
  personId: string;
  personName: string;
  paidCents: number;
  shareCents: number;
  /** paid - share: positive means this person is owed money */
  netCents: number;
  /** Only set for percentage method */
  percentage?: number;
}

export interface Transfer {
  fromName: string;
  toName: string;
  amountCents: number;
}

export interface SettlementRecord {
  id: string;
  periodType: PeriodType;
  /** yyyy-mm for months, yyyy-Www for ISO weeks */
  period: string;
  method: SplitMethod;
  totalSharedCents: number;
  results: PersonResult[];
  transfers: Transfer[];
  /** ISO timestamp of when the calculation was saved */
  createdAt: string;
  /** ISO timestamp of when the transfers were actually paid */
  settledAt?: string;
}

/** A savings goal with manual and optional automatic contributions */
export interface Goal {
  id: string;
  name: string;
  targetCents: number;
  savedCents: number;
  /** Optional target month (yyyy-mm) */
  deadline?: string;
  /** Premium: contribute this amount automatically every month */
  monthlyAutoCents?: number;
  /** Last month (yyyy-mm) an automatic contribution was applied */
  lastAutoMonth?: string;
}

export interface AppSettings {
  themeMode: 'light' | 'dark' | 'auto';
  /** Whether the first-launch setup has been completed */
  onboarded: boolean;
  /** ISO 4217 code of the display currency */
  currencyCode: string;
  /** Require biometric/device unlock when opening the app */
  appLock: boolean;
  /** Notify when a category budget is nearly or fully spent */
  budgetAlerts: boolean;
  /** Monthly reminder to settle up shared expenses */
  settleReminder: boolean;
  /** Sunday summary of the week's spending */
  weeklyDigest: boolean;
  /**
   * Month (yyyy-mm) from which unspent budget carries into the next month.
   * A month rather than a flag: carry-over may only count months the user
   * actually opted into, otherwise switching it on would back-date a
   * windfall from months they never budgeted.
   */
  budgetRolloverFrom?: string;
  /**
   * App version whose release notes have been shown. Absent on installs
   * predating the what's-new screen, which is treated as "show the current
   * release", not "show everything ever".
   */
  lastSeenVersion?: string;
  /** One-time Budget Pro purchase / unlock */
  premium: boolean;
}

/** Alert level already sent for a "yyyy-mm:categoryId" key, to avoid repeats */
export type BudgetAlertLog = Record<string, 'near' | 'over'>;

export interface AppState {
  people: Person[];
  accounts: Account[];
  accountTransfers: AccountTransfer[];
  transactions: Transaction[];
  settlements: SettlementRecord[];
  recurring: RecurringRule[];
  templates: EntryTemplate[];
  customCategories: Category[];
  /** Monthly spending limit in cents per category id */
  budgets: Record<string, number>;
  goals: Goal[];
  budgetAlertLog: BudgetAlertLog;
  settings: AppSettings;
}
